version: '3.8'

services:
  bomb_panel:
    build: .
    ports:
      - "8000:80"
    volumes:
      # Mapeia a pasta ./src local para a pasta do Apache no container
      - ./src:/var/www/html
    networks:
      - ctf_net

networks:
  ctf_net:
    driver: bridge